owasp-top10-2021-apps/a3/rate-my-cake/app/config/routes.rb
Rails.application.routes.draw do
  resources :rates
  root 'rates#index'
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/models/rate.rb
class Rate < ApplicationRecord
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/controllers/rate_controller.rb
class RateController < ApplicationController
  def index
  end
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_action :set_rate, only: %i[ show edit update destroy ]

  # GET /rates or /rates.json
  def index
    @rates = Rate.all
  end

  # GET /rates/1 or /rates/1.json
  def show
  end

  # GET /rates/new
  def new
    @rate = Rate.new
  end

  # GET /rates/1/edit
  def edit
  end

  # POST /rates or /rates.json
  def create
    @rate = Rate.new(rate_params)

    respond_to do |format|
      if @rate.save
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully created." }
        format.json { render :show, status: :created, location: @rate }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rates/1 or /rates/1.json
  def update
    respond_to do |format|
      if @rate.update(rate_params)
        format.html { redirect_to rate_url(@rate), notice: "Rate was successfully updated." }
        format.json { render :show, status: :ok, location: @rate }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1 or /rates/1.json
  def destroy
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url, notice: "Rate was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rate
      @rate = Rate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rate_params
      params.require(:rate).permit(:rate, :comment, :text)
    end
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/helpers/application_helper.rb
module ApplicationHelper
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/helpers/rate_helper.rb
module RateHelper
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/helpers/rates_helper.rb
module RatesHelper
end

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body>
  
    <nav class="navbar navbar-dark bg-dark">
      <h1>Rate my cake ! 🎂</h1>
    </nav>

    <%= yield %>
  </body>
</html>

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/rates/_form.html.erb
<%= form_with(model: rate, local: true) do |form| %>
  <% if rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rate, class: "form-label"%>
    <%= form.number_field :rate, class: "form-range", type: "range", min: "0", max:"5"%>
  </div>

  <div class="field">
    <%= form.label :comment, class: "form-label"%>
    <%= form.text_area :comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/rates/edit.html.erb
<h1>Editing Rate</h1>

<%= render 'form', rate: @rate %>

<div class="buttons-container">
    <%= button_to "Show", @rate, :class => "col btn btn-primary", :method => :get %>
    <%= button_to "Back", rates_path, :class => "col btn btn-primary", :method => :get %>
</div>

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/rates/index.html.erb
<div class="container-fluid">
  <div class="comment-container">
    <div class="comment-img">
      <%= image_tag("rainbow_cake.jpg", :class => "img-thumbnail") %>
    </div>
    <div class="comment">
      <div class="comment-profile-pic">
        <%= image_tag "cakelover.png" %>
        <div class="comment-profile-pic-username">Cakelover</div>
      </div>
      <div class="comment-description">
        Hey 🖐 ! <br />
        It took some <b>effort</b> but i finally made it. <br />
        Rate my rainbow cake !
      </div>
    </div>
  </div>

  <% @rates.each do |rate| %>
    <div class="comment-container">
      <div class="comment darker">
        <div class="comment-profile-pic">
          <%= image_tag "kind_user.png" %>
          <div class="comment-profile-pic-username">kind_user</div>
        </div>
        <div class="comment-description">
          <b>Rate:</b> <%= rate.rate %> <br>
          <p> <%= raw rate.comment %> </p>
          <%= link_to 'Show', rate %>
          <%= link_to 'Edit', edit_rate_path(rate) %> 
          <%= link_to 'Destroy', rate, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="button-wraper">
    <%= button_to "Leave a rate", new_rate_path, :class => "btn btn-primary", :method => :get %>
  </div>

</div>

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/rates/new.html.erb
<div class="container-fluid">
    <h1>New Rate</h1>

    <%= render 'form', rate: @rate %>
    
    <div class="buttons-container">
        <%= button_to "Back", rates_path, :class => "btn btn-primary", :method => :get %>
    </div>
</div>

owasp-top10-2021-apps/a3/rate-my-cake/app/app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>

<div class="centered" >
  <p>
    <strong>Rate:</strong>
    <%= @rate.rate %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= @rate.comment %>
  </p>
</div>

<div class="buttons-container">
    <%= button_to "Edit", edit_rate_path(@rate), :class => "col btn btn-primary", :method => :get %>
    <%= button_to "Back", rates_path, :class => "col btn btn-primary", :method => :get %>
</div>